version: '3.9'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - REACT_URL=http://localhost:3000
      - REACT_URL_S=https://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "8080:8080"
    networks:
      - pomodoro_net

  redis:
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - pomodoro_net

networks:
  pomodoro_net:
    driver: bridge

volumes:
  cache:
    driver: local